#!/usr/bin/expect 
spawn ssh judec@av-lab26
expect "password"
send "NICEwork94\r"
expect "$"
send "sudo nvme id-ctrl /dev/nvme0n1 >> file.txt 2>&1\r"
expect ":"
send "NICEwork94\r"
expect "$"
send "logout\r"

